version: '3'

services:

  rankingv1:
    image: tensorflow/serving
    container_name: rankingv1
    command: tensorflow_model_server --port=8500 --rest_api_port=8501 --model_name=rankingv1 --model_base_path=/models/rankingv1
    ports:
      - "8501:8501"
      - "8500:8500"
    environment:
      - MODEL_NAME=rankingv1
    volumes:
      - /home/jaco/Projetos/realDeployML/realDeployML/models/rankingv1/:/models/rankingv1