version: '3.8'
#run:
#sudo docker compose -f ~/Projetos/realDeployML/realdeployml/tools/bareBones/bareBonesDocker.yml up -d --build
#stop:
#sudo docker stop $(sudo docker ps -a -q)
#remove:
#sudo docker rm $(sudo docker ps -a -q)
#remove remove:
#sudo docker system prune -a --volumes
#get stdout logs:
#sudo docker logs 5757c411ebbe
#run bash:
#sudo docker exec -t -i rankingv1 /bin/bash

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - /home/jaco/Projetos/realDeployML/realdeployml/tools/bareBones/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      - my-network
    depends_on:
      - flask
      - flask1
      - flask2

  flask:
    image: jacobiu/baseimagedeploy:latest
    container_name: flask
    working_dir: /home/jaco/Projetos/realDeployML/
    command: gunicorn --bind 0.0.0.0:5000 "realdeployml.tools.bareBones.app:create_app()" #checar se da pra passar um parametro qui do modelo
    expose:
      - 5000
    volumes:
      - /home/jaco/Projetos/realDeployML/:/home/jaco/Projetos/realDeployML/
    networks:
      my-network:
        aliases:
          - flask-app

  flask1:
    image: jacobiu/baseimagedeploy:latest
    container_name: flask1
    working_dir: /home/jaco/Projetos/realDeployML/
    command: gunicorn --bind 0.0.0.0:5000 "realdeployml.tools.bareBones.app:create_app()"
    expose:
      - 5000
    volumes:
      - /home/jaco/Projetos/realDeployML/:/home/jaco/Projetos/realDeployML/
    networks:
      my-network:
        aliases:
          - flask-app

  flask2:
    image: jacobiu/baseimagedeploy:latest
    container_name: flask2
    working_dir: /home/jaco/Projetos/realDeployML/
    command: gunicorn --bind 0.0.0.0:5000 "realdeployml.tools.bareBones.app:create_app()"
    expose:
      - 5000
    volumes:
      - /home/jaco/Projetos/realDeployML/:/home/jaco/Projetos/realDeployML/
    networks:
      my-network:
        aliases:
          - flask-app

networks:
  my-network: